spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        jpa:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
